//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3603
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNC.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CNC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _12359 {
            get {
                object obj = ResourceManager.GetObject("12359", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _12360 {
            get {
                object obj = ResourceManager.GetObject("12360", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _12361 {
            get {
                object obj = ResourceManager.GetObject("12361", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _12362 {
            get {
                object obj = ResourceManager.GetObject("12362", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 30.01.09
        ///--------
        ///vitesse maxi si Z&gt;=0
        ///selectedIndex centré dans lBoxFichier
        ///ajout listBox A Propos De
        /// 
        ///31.01.09
        ///--------
        ///utilisation linq pour mettre à jour Params Axes
        ///ajout pBoxPhoto sur AProposDe
        /// 
        ///09.02.09
        ///--------
        ///ajout LOG.txt
        ///suppression delegate affichage temps periode usinage dans c_usinage qui ralentit ordi
        /// 
        ///04.03.09
        ///--------
        ///creation class pour usinage, dessin, IOW
        ///traitement direct IOW.dll
        /// 
        ///10.06.09
        ///--------
        ///class iowUSB30.01.09
        ///--------
        ///vitesse maxi si Z&gt;=0
        ///selecte [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string AProposDe {
            get {
                return ResourceManager.GetString("AProposDe", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap cnc {
            get {
                object obj = ResourceManager.GetObject("cnc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à firm 2.0
        ///--------
        /// 
        ///gestion fraction de pas (1/8)
        ///reglage externe pulse High, Low, Idle.
        /// </summary>
        internal static string fimwarePic {
            get {
                return ResourceManager.GetString("fimwarePic", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap loupeMoins {
            get {
                object obj = ResourceManager.GetObject("loupeMoins", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loupePlus {
            get {
                object obj = ResourceManager.GetObject("loupePlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
